### ISSUE TITLE
A patches page

### ISSUE THREAD

**Issue by granny** [pl3xgaming/PurpurDocs#4]
This page would explain every patch that Purpur adds with a categorized list of the feature, performance stuff, API stuff, etc.

It would be categorized by `api` & `server`, with headers being the filename of the patch. Each patch would include a hyperlink to the patch in Purpur.

```
/patches
## api
  ### This-Is-A.patch
    description:
    reason?:
    permissions:
    options:
  ### This-Is-Another.patch
    description:
    reason?:
    permissions:
    options:
## server
  ### This-Is-A.patch
    description:
    reason?:
    permissions:
    options:
  ### This-Is-Another.patch
    description:
    reason?:
    permissions:
    options:
```

Truncating the number from the filename would make it less difficult to keep it up-to-date with Purpur incase patches get reorganized or renamed.

* `description` will explain what that patch does
* `reason` will explain why this patch was added
* `permissions` will list any permissions that the patch adds
* `options` will list any options that the patch adds

Not really sure how to format this page but these are my inital thoughts. The format may change from what is listed here depending on feedback from others or how it looks in the end.
